apiVersion: v1
kind: ServiceAccount
metadata:
  name: kove-extended-resource-controller-sa
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kove-extended-resource-master
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - nodes/status
    verbs:
      - get
      - list
      - patch
      - update
  - apiGroups:
      - topology.node.k8s.io
    resources:
      - noderesourcetopologies
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - nfd.openshift.io
    resources:
      - nodefeaturerules
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kove-extended-resource-master
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kove-extended-resource-master
subjects:
  - kind: ServiceAccount
    name: kove-extended-resource-controller-sa
    namespace: kube-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kove-extended-resource-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kove-extended-resource-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: kove-extended-resource-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kove-extended-resource-controller
    spec:
      serviceAccountName: kove-extended-resource-controller-sa
      priorityClassName: system-node-critical
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: kove-extended-resource-controller
          image: quay.io/ecosystem-appeng/kove-extended-resource-controller:latest
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: In
                    values:
                      - ""
