apiVersion: apps/v1
kind: Deployment
metadata:
  name: kove-extended-resource-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kove-extended-resource-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: kove-extended-resource-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kove-extended-resource-controller
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: kove-extended-resource-controller
          image: quay.io/ecosystem-appeng/kove-extended-resource-controller:latest
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: In
                    values:
                      - ""
