apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: lockers.example.crd.com
spec:
  group: example.crd.com
  scope: Namespaced
  names:
    kind: Locker
    listKind: LockerList
    plural: lockers
    singular: locker
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["consumed","allocatable"]
          properties:
            consumed:
              type: integer
              minimum: 1
            allocatable:
              type: integer
              minimum: 1
  versions:
    - name: v1alpha1
      served: true
      storage: true